### PR TITLE
Added suggestion for a solution to localized languages

### PR DESCRIPTION
**Pull request by baardhermansen**
After participating in issue #50 regarding localized account names, i was tempted to look into it. 
This PR is a suggestion that uses English, German and Spanish as examples. 
Basically, the change utilizes the PowerShell command [Import-LocalizedData](https://learn.microsoft.com/powershell/module/microsoft.powershell.utility/import-localizeddata), which is available from PowerShell 3.0 and onwards.

As you'll notice, the SYSTEM account name remains unchanged. The reason for that is that i did not see any localization of the account name i neither Spanish nor German Server 2016.

I also used VS Code's "Format Document" so the number of additions and deletions makes it look a lot worse than it is!

### CODE REVIEW

**Comment by GeoSimos** [comment]
Hi @baardhermansen,

Thank you for your pull request, it is really appreciated, however it complicates significantly the solution because we will end up with multiple install-psd.ps1 files for each language.
As we have stated initially, the solution is based on English US language O/S, the ability to work on localized versions should be handling the localized user accounts/groups, besides that we are working on a newer installer and will cover this functionality without over-engineering it.

**Comment by baardhermansen** [comment]
> Hi @baardhermansen,
> 
> Thank you for your pull request, it is really appreciated, however it complicates significantly the solution because we will end up with multiple install-psd.ps1 files for each language. 

There will be multiple Install-PSD.ps**d**1 files, each residing in its language folder. 
That's because of the way Import-LocalizedData works; each language file must have the same name as the calling .ps1 file. 

> As we have stated initially, the solution is based on English US language O/S, the ability to work on localized versions should be handling the localized user accounts/groups, besides that we are working on a newer installer and will cover this functionality and avoid over-engineering it.

I get that.
The suggested solution just made it easy for people to add new languages without touching 'Install-PSD.ps1'.
But hey, at least i learnt something new :)

**Comment by GeoSimos** [comment]
> I get that. The suggested solution just made it easy for people to add new languages without touching 'Install-PSD.ps1'. But hey, at least i learnt something new :)

We really appreciate your effort, that's the spirit, to learn new things!

**Comment by baardhermansen** [comment]
@jens-mueller I really like it, pretty short and easy to implement.

**Pull request closed without merging**
