### PR TITLE
Updated readability on all but Scripts folder

### PR DESCRIPTION
**Pull request by Raynefire14**
Fixed/Standardized capitalization, spelling errors, punctuation, and grammar.(Comments, Log/Verbose Messages)

Reworded some phrases for clarity.

Expanded cmdlet aliases for readability (dir > Get-ChildItem, where > Where-Object, foreach > ForEach-Object)

Worked through all files except for scripts folder.

### CODE REVIEW

**Comment by Raynefire14** [comment]
I just realized that I shouldn't have changed ForEach to ForEach-Object as the script was using the statement rather than the cmdlet alias.

**Comment by soupman98** [comment]
Thanks so much for your review and contributions @Raynefire14. Your time and input helps to improve PSD!!

We're incorporating many of your documentation changes and edits and reviewing installer script suggestions.

**Comment by Hammarskjold** [comment]
Are we merging this or was that done by manual merge and this PR should be closed off?

**Comment by arwidmark** [comment]
Since we had many iterations of the documentation, I've added these changes manually. Thank you for the help.

**Pull request closed without merging**
